.circleci/config.yml, ci/circle_build_linux.sh
=> Add circleci config

ci/circle_build_linux.sh, test-requirements.txt
=> Upload coverage to codecov

fletcher/_algorithms.py, fletcher/base.py, fletcher/string_array.py, tests/test_pandas_integration.py
=> Extract base functionality into an FletcherExtensionArray

fletcher/_algorithms.py, fletcher/base.py, fletcher/string_array.py, tests/string_array/test_pandas_extension.py
Closes #31 #30 
* Workaround for slicing with steps unequal to one
* Indexing using integer arrays
* constructor now accepts array-like objects
=> Multiple fixes

fletcher/base.py, setup.py, test-requirements.txt, tests/test_base.py, tests/test_pandas_extension.py, tests/test_pandas_integration.py
=> Implement __setitem__

README.md, setup.py
=> Add README in setup.py

tests/test_numba_integration.py
=> Compability with py.test 4.0

ci/circle_build_linux.sh, fletcher/base.py, setup.py, tests/test_pandas_extension.py
=> Update to pandas==0.24, pyarrow==0.12

.gitlab-ci.yml, ci/circle_build_linux.sh
=> Add gitlab CI

.github/CODEOWNERS
@chmp Do you also want to be a default reviewer again?
=> Add default reviewers

docs/index.rst, docs/motivation.rst
=> Add documentation about the long-term goal of fletcher

fletcher/__init__.py
=> Add __version__

README.md
=> Mention asv and pre-commit in README.md

fletcher/base.py, tests/test_pyarrow_roundtrip.py
=> Allow arrow and parquet roundtrips

benchmarks/benchmarks.py, fletcher/string_array.py, tests/test_text.py
=> Add naive zfill implementation

benchmarks/benchmarks.py, fletcher/_algorithms.py, fletcher/algorithms/string.py, fletcher/string_array.py, tests/test_text.py
=> Add numba implementation for contains(.., regex=False, case=True)

.codecov.yml, tests/test_algorithms.py
add codecov.yml to reduce failing coverage reports due to hypothesis and changing test data
=> Add codecov.yml

fletcher/algorithms/string_builder.py, fletcher/string_array.py, tests/test_text.py
=> Fix tests for non-breaking space

fletcher/base.py
The function `pyarrow.types.is_list` returns `False` if given a LargeListArray which can be problematic in this repo because some functions check whether or not the underlying data of the FletcherArray is a ListArray.
In this PR, we define a property `_is_list` for a `FletcherDType` that returns `True` whenever given a ListArray or a LargeListArray.
=> Support for LargeListArray

fletcher/base.py
This should fix the issues in the nightly builds.
=> Implement isnan ufunc

CHANGELOG.md, fletcher/base.py
=> Create a shallow copy on `.astype(equal dtype, copy=True)`

CHANGELOG.md, fletcher/base.py
=> Fix pad_1d import error

benchmarks/benchmarks.py, fletcher/base.py, fletcher/string_array.py, fletcher/string_mixin.py, tests/test_text.py
=> Implement str accessor (requires pandas master / 1.2+)

CHANGELOG.md, environment.yml, fletcher/string_array.py, tests/test_text.py
=> Fix wrong/dropping index during calls of split/extractall 

CHANGELOG.md
=> Release 0.6.2

CHANGELOG.md, fletcher/string_array.py, fletcher/string_mixin.py, tests/test_text.py
=> Use is* functions from Arrow

CHANGELOG.md, fletcher/base.py, tests/test_pandas_integration.py
=> Simplify factorize call

CHANGELOG.md, fletcher/base.py, tests/conftest.py, tests/test_pandas_extension.py
=> Switch to pd.NA as na_value

tests/test_pandas_extension.py
=> Fix nightly tests

.github/workflows/ci.yml, .github/workflows/cron.yml, CHANGELOG.md, ci/circle_build_linux.sh, fletcher/algorithms/string.py, fletcher/base.py, fletcher/string_mixin.py, tests/test_pandas_extension.py
=> Fix nightly failures

.pre-commit-config.yaml, fletcher/base.py, fletcher/string_array.py, tests/test_algorithms.py, tests/test_pandas_extension.py
Took inspiration from https://github.com/pandas-dev/pandas/pull/39350
=> Fix tests to work with pandas master

.gitignore
Checklist
* [ n/a] Added a `CHANGELOG.md` entry
=> add vscode project settings to .gitignore
