- README.md
- fletcher/base.py
- setup.cfg
- tests/conftest.py
- tests/string_array/test_pandas_extension.py
* This adds all tests provided by pandas itself to validate their interface.
* On my machine it terminates at some point with a segfault :/
* I marked all tests as xfail until we can pin it down to a few tests
* We should consider putting each of the test cases into it's own module. for now, this would be fine for me though
Not sure if we can merge, yet. The segfault probably messes up the build entirely
> Add pandas interface tests

- fletcher/base.py
- fletcher/string_array.py
- tests/string_array/test_pandas_extension.py
I'm assuming here that the current StringArray is only of type `unicode`. I believe we should provide two distinct types, e.g. `StringArray` and `BytesArray`. Implementation for both should be mostly the same, though.
5 interface test classes green
5 to go
> Pandas interface __getitem__

- benchmarks/benchmarks.py
- fletcher/base.py
Fixes a recently introduced performance regression.
> Use fast path for item.step = None

- .circleci/config.yml
- .pre-commit-config.yaml
- ci/circle_build_linux.sh
- fletcher/base.py
- tests/test_pandas_extension.py
Adds tests for list, int64 and float64 types. Sadly they all fail on all pandas releases. I have marked the failures and will fix them upstream.
Fixes #43 
Fixes #44 
Fixes #46 
Fixes #11
> Test against Pandas nightly

- benchmarks/benchmarks.py
- fletcher/base.py
- tests/test_base.py
This adds benchmarks for get/seitem and improves performance of setitem by upto a factor of 5. We're still *far* away from where we should be but with these changes we're basically limited in how fast `arrow->pandas->arrow` conversion is done
The _complexity_ of the benchmark setup is there to receive better output since the parameters are strings instead of arrays
> Get and setitem performance

- environment.yml
I think it'd be useful to have a conda environment file, so an environment with all the dependencies can be simply created with `conda env create` from the repo directory.
> Adding conda environment file

- fletcher/base.py
- tests/test_base.py
Fixing typo in exception message:
```
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fletcher
>>> fletcher.FletcherArray(None)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\DDrive\msys2\home\UKC2892\src\fletcher\fletcher\base.py", line 172, in __init__
"Unsupported type passed for {}: {}".format(self.__name__, type(array))
AttributeError: 'FletcherArray' object has no attribute '__name__'
```
> Fixing typo when raising a ValueError in FletcherArray constructor

- tests/test_pandas_extension.py
With the object conversion path refacter, Arrow now returns the same
date type when created from a list and a numpy array. Sadly this is
different to what we use as the reference type in our tests. To fix the
root of the problem, the Pandas tests should be adjusted to pass in the
dtype in their calls to `_from_sequence`.
> Handle change in default type of dates

- fletcher/base.py
- tests/test_pandas_extension.py
The respective PR was merged. Maybe too late to make it into today's nightly but CI will tell.
> Enable int64 and float64 tests for Pandas nightly

- fletcher/base.py
- tests/test_pandas_extension.py
- tests/test_pandas_integration.py
pytest>=3.7.0 includes more recent pyflakes detecting F821 (undefined name) in typing comments.
> Pytest 3.7 and higher

- fletcher/base.py
xref https://github.com/pandas-dev/pandas/pull/28389
> REF: implement size for 2D compat

- fletcher/base.py
- tests/test_pandas_extension.py
- tests/test_pandas_integration.py
* introduce unique on FletcherArray
* using only true copy that's required by ExtensionArray
This solves issue https://github.com/xhochy/fletcher/issues/25. We define `self.unique()` using `pyarrow.unique()` and add some tests for this function. Also we remove the boolean `deep` in `self.copy()` as it is not needed in pandas' specification of ExtensionArray.
> introduce unique on FletcherArray

- fletcher/_algorithms.py
- tests/test_pandas_integration.py
* using null_count in isnull extractor
We use `null_count` in `self.extract_isnull_bytemap` to speed up some cases. Plus, we add more tests and clean some.
> using null_count in isnull extractor

- benchmarks/take.py
- fletcher/base.py
- fletcher/string_array.py
This improves the take performance of continuous arrays so that it performs similar to the `take` implementation of `pd.Series` based on `np.ndarray` with native datatypes. For chunked arrays, we still will either need a better Take kernel in Arrow or #91 .
> Implement take for continuous arrays

- .github/workflows/ci.yml
Currently we only build on pull request and thus are sometimes missing the coverage statistics in PRs.
> Also build on master

- tests/test_text.py
These tests run sometimes a tiny bit more than a second under CPU load. That's fine, don't fail them for that.
> Ignore deadline for str-hypothesis tests

- tests/test_pandas_extension.py
Changed test_arith_series_with_array function to convert the data to int64, when running on Windows.
> Work-around for testing of arithmetic operations

- tests/test_pandas_extension.py
As requested by @xhochy , a new pull request with a better fix for the Windows integer arithmetic issue in the unit tests.
> Better fix for Windows integer arithmetic issue in unit tests

- fletcher/string_array.py
- tests/test_text.py
Renamed existing TextAccessor from 'fr_text' to 'fr_strx'.
Added an extended TextAccessor 'fr_str' that works with fletcher and object series. If no flechter version of the str function is available, the fletcher series is converted to pandas and back to use the existing pandas implementation as fallback.
Feedback very welcome!
> User friendly string accessor

- .github/workflows/ci.yml
- fletcher/string_array.py
- tests/test_text.py
Adressing #166. This sets up minimal testing on windwos runners without aiming to provide code coverage, using nightlies and testing pre-commit hooks. The goal is to run `pytest` to spot rare issues on widows systems we encoutered last days. Since `fletcher` itself is OS angostic except its dependencies the windows ci job is some kind of optional and not in sync with the linux ci script.
And adds missing white space character of [failed build](https://github.com/xhochy/fletcher/runs/881171847?check_suite_focus=true#step:3:1175).
> run basic test setup on windows

- fletcher/base.py
Right now, we can't instantiate a FletcherArray with a DictionaryArray. For example, the code
```
import fletcher as fr
import pyarrow as pa
fr.FletcherContinuousArray(pa.array([1,2]).dictionary_encode())
```
fails with `KeyError: 26`, this is the id of the DictionaryArray type in pyarrow and it is missing in the `_python_type_map`.
Same thing with `LargeListArray` when we try to instantiate a `pd.Series`, the code 
```
import pandas as pd 
import fletcher as fr
import pyarrow as pa
pd.Series(fr.FletcherContinuousArray(pa.LargeListArray.from_arrays([1,2], [1,2])))
```
fails with `KeyError: 33` which is the id of the LargeListArray type in pyarrow and it is missing in the `python_type_map`.
Finally the `kind` function in `FletcherBaseDtype` fails for LargeListArrays because the function …
> Dictionary and LargeList instantiation

- fletcher/base.py
Right now, one can't use `__getitem__` with a `np.int` when using a `FletcherChunkedArray`. This is because it fails at pyarrow level. More precisely, the following code works fine
```
import pyarrow as pa
import numpy as np
pa.array([1,2])[np.int32(0)]
```
but this one
```
import pyarrow as pa
import numpy as np
pa.chunked_array(pa.array([1,2]))[np.int32(0)]
```
fails with error `TypeError: key must either be a slice or integer`.
The hotfix provided in this PR is to cast `item` to `int` before applying getitem but maybe this should be fixed directly in pyarrow ?
> [hotfix] Casting item to int in __getitem__ if is_integer is true

- fletcher/base.py
- tests/test_base.py
Introducing flatten for `FletcherContinuousArray` and `FletcherChunkedArray` by using `pa.Array.flatten()`.
> introducing flatten for FletcherArray

- CHANGELOG.md
- fletcher/string_array.py
- tests/test_text.py
This PR resolves #192. The fallback mechanism using `str` functions sometimes yields a `pd.Dataframe` (e.g. `extractall`) which will be converted to the accoring `fletcher` types.
Checklist
> Add support for string functions returning dataframes

- tests/test_pandas_extension.py
This fails partly to us not supporting item access on lists yet and also because views are not handled properly in fletcher.
Checklist
> xfail test_transpose

- CHANGELOG.md
- fletcher/_algorithms.py
- fletcher/base.py
- tests/test_algorithms.py
- tests/test_base.py
In this draft PR we test the use of numba and parallelism with ListArrays.
We implemented a fast take on pyarrow.ListArrays with numeric type and no nulls.  
For the benchmark, we used the following code 
```
import pandas as pd
res = pd.DataFrame()
for density in [0.001, 0.01, 0.1, 0.5, 1, 10, 100, 1000]:
for len_list_array in range(5,10):
if density * 10**size_list_array <= 10**9:
values = np.random.randint(0, 10**5, int(density * 10**size_list_array))
offsets = np.sort(np.random.randint(0, len(values)+1, 10**size_list_array))
list_array = pa.ListArray.from_arrays(pa.array(offsets), pa.array(values))
for ratio_ind_length in [0.1 * k for k in range(1, 10)]:
indices = pa.array(np.random.randint(0, len(list_array), 
int(len(list_array) * ratio_ind_length))
)
t = time() …
```
> Fast take for list_array with no nulls and numeric type

- fletcher/_algorithms.py
- tests/test_base.py
thanks for merging https://github.com/xhochy/fletcher/pull/180 !
I updated it with the fix of the overflow (exactly the same problem as in https://issues.apache.org/jira/browse/ARROW-10494).
I could add a test on this but it will take some time and memory to run.
```python
from fletcher._algorithms import take_on_pyarrow_list, pa, np
arr = pa.array([np.arange(x).astype(np.int8) for x in range(6)])
nb_repeat = 2**32 // arr.offsets.to_numpy()[-1]
indices = np.repeat(np.arange(len(arr)), nb_repeat)
take_on_pyarrow_list(arr, indices).validate()  # more than 1min30s
```
> fixing upcast for fast-take on list

- CHANGELOG.md
- fletcher/algorithms/string.py
- tests/test_text.py
> Add helper to broadcast binary ops with numba

- CHANGELOG.md
- fletcher/base.py
- tests/test_pandas_integration.py
Fixes #213
Checklist
cc @lbittarello @jtilly
> Allow NumPy ufuncs to work with `np.ndarray` outputs where operations are clearly defined
